### ISSUE TITLE
Dev.ts 가 정상 작동을 하지 않음

### ISSUE THREAD

**Issue by NOOBNUBY** [star0202/cts-template#58]
>TypeError: Cannot read properties of undefined (reading 'deferReply')

**Comment by star0202** [comment]
해당 오류는 eslint + prettier 조합에서 biome으로 migrate할때 biome이 자동으로 `ChatInputCommandInteraction`을 type import하도록 수정해 발생한 것으로 추정됩니다
(command의 argument type이 JavaScript로 트랜스파일되었을 때 접근할 수 없다면 interaction이 undefined가 되는 command.ts의 이슈입니다)

따라서 해당 이슈는 `ChatInputCommandInteraction`을 type import하지 않도록 하면 해결될 것으로 보이며, 추후에 템플릿을 수정하도록 하겠습니다

**Comment by star0202** [comment]
PR을 보내주셨군요 확인하겠습니다
